controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_command_controller:
      type: forward_command_controller/ForwardCommandController

forward_command_controller:
  ros__parameters:
    interface_name: effort
    joints:
      - joint_coxa_R1
      - joint_femur_R1
      - joint_tibia_R1
      - joint_coxa_R2
      - joint_femur_R2
      - joint_tibia_R2
      - joint_coxa_R3
      - joint_femur_R3
      - joint_tibia_R3
      - joint_coxa_L1
      - joint_femur_L1
      - joint_tibia_L1
      - joint_coxa_L2
      - joint_femur_L2
      - joint_tibia_L2
      - joint_coxa_L3
      - joint_femur_L3
      - joint_tibia_L3